### ISSUE TITLE
IMP-Sales & Shipping - SDD

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Aspee#13]
Sales   & Shipping - SDD

SDD :

[ASPEE_SALES AND SHIPPING SDD_V1.0.pdf](https://github.com/astpl1998/Aspee/files/5701133/ASPEE_SALES.AND.SHIPPING.SDD_V1.0.pdf)

**Comment by srinivasanbaskaran** [comment]
@raju-kurup .. 

SDD closed & Sent to Customer

**Comment by raju-kurup** [comment]
As per the termination letter given by ASPEE on 11.03.2021 @10.39 by email. We are closing this ticket.
