### ISSUE TITLE
IMP-Discrete Production - Business Process Study

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Aspee#21]
Discrete   Production Business Process Study Discussion held on

**Questionnaire :**

**Rec Video :**

**MOM :**

**Comment by Duraisingam-G** [comment]
Sir,
Business process study completed, MOM Mail sent on 10.11.2020.
[ASPEE_MOM_Discrete_Production dt 10.11.2020 v 1.0.docx](https://github.com/astpl1998/Aspee/files/5634046/ASPEE_MOM_Discrete_Production.dt.10.11.2020.v.1.0.docx)

**Comment by raju-kurup** [comment]
As per the termination letter given by ASPEE. We are closing this ticket.
