### ISSUE TITLE
IMP-Finance and Accounts - Business Process Study

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Aspee#24]
Finance   and Accounts Business Process Study Discussion held on

**Questionnaire :**
**Rec Video :**
**MOM :**

**Comment by Dhanwandher** [comment]
Sir,
Business process study completed, MOM Mail sent on 02.11.2020, 04.11.2020, 11.11.2020, 03.11.2020, 04.11.2020
[MOM.zip](https://github.com/astpl1998/Aspee/files/5701400/MOM.zip)
[Final.zip](https://github.com/astpl1998/Aspee/files/5701401/Final.zip)

**Comment by raju-kurup** [comment]
As per the termination letter given by ASPEE. We are closing this ticket.
