### ISSUE TITLE
IMP-Finance and Accounts - SDD

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Aspee#25]
Finance   and Accounts - SDD

**SDD :**

**Comment by Dhanwandher** [comment]
Dear Sir,

SDD Prepared, Pl review.

[SDD.zip](https://github.com/astpl1998/Aspee/files/5701599/SDD.zip)

**Comment by raju-kurup** [comment]
As per the termination letter given by ASPEE. We are closing this ticket.
