### ISSUE TITLE
MRP Script - Dcube

### ISSUE THREAD

**Issue by Duraisingam-G** [astpl1998/Aspee#36]
Dear karthi,
As discussed, Pl find the attached MRP Script to be run from dcube for ASPEE MRP Planning.
Using this option to avoid the script from back end each every time. 

MRP Planning Run Name will be given manually from users in dcube. 
In the attached Script MRP Planning Run name : **MRP9**
[MRP Script.txt](https://github.com/astpl1998/Aspee/files/5729787/MRP.Script.txt)

**Comment by raju-kurup** [comment]
As per the termination letter given by ASPEE.  We are closing this ticket.
