### ISSUE TITLE
IMP-Purchase & Subcontract - Business Process Study 

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Aspee#6]
Purchase &   Sub Contract Business Process Study Discussion held on 28-10-2020 and 29-10-2020

**Questionnaire :** [Purchase & Subcontract - Questionaire.xlsx](https://github.com/astpl1998/Aspee/files/5464955/Purchase.Subcontract.-.Questionaire.xlsx)

**Rec Video :** https://drive.google.com/file/d/1rQiZNwaElmabPxNPzrS6h7dDYMP-k4f_/view?usp=sharing

**Minutes Of Meeting :** 

MOM_1: [01_ASPEE_MOM_PUR_SUB_29.10.2020_V 1.0.docx](https://github.com/astpl1998/Aspee/files/5465692/01_ASPEE_MOM_PUR_SUB_29.10.2020_V.1.0.docx)

MOM_2: [02_ASPEE_MOM_PUR_SUB_29.10.2020_V 1.0.docx](https://github.com/astpl1998/Aspee/files/5465708/02_ASPEE_MOM_PUR_SUB_29.10.2020_V.1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Herewith I have attached the Business Process Study of Purchase & Subcontracting Documents & Link

Kindly check & close this ticket

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
As per the termination letter given by ASPEE on 11.03.2021 @10.39 by email. We are closing this ticket.
