### ISSUE TITLE
IMP-Inventory & PICC - Business Process Study

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Aspee#9]
Inventory &   Stores Business Process Study Discussion held on 30-10-2020

**Questionnaire :** [Inventory & PICC_Updated.xlsx](https://github.com/astpl1998/Aspee/files/5515345/Inventory.PICC_Updated.xlsx)

**Rec Video :** https://drive.google.com/file/d/1tm7C8VGq-kmrJ1ASleIe4FppJeTKjq1X/view?usp=sharing

**MOM :**  [01_ASPEE_MOM_INV_02.11.2020_v1.0.docx](https://github.com/astpl1998/Aspee/files/5515378/01_ASPEE_MOM_INV_02.11.2020_v1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Herewith I have attached all the documents & Link of the Inventory & PICC Business Process Study

Kindly check & Close this ticket

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
As per the termination letter given by ASPEE on 11.03.2021 @10.39 by email. We are closing this ticket.
